/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2025-08-20 05:31:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.frontend;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/frontend/header.jsp", Long.valueOf(1753415364102L));
    _jspx_dependants.put("/frontend/footer.jsp", Long.valueOf(1751597016064L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1308849601000L));
    _jspx_dependants.put("jar:file:/C:/Users/n21dc/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Login</title>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, shrink-to-fit=yes\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery.validate.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"https://js.hcaptcha.com/1/api.js\" async defer></script>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/pageLoad.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/custom_background_template.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/custom_row_template.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/custom_border_template.css\"/>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        .error {\r\n");
      out.write("            color: red;\r\n");
      out.write("            font-size: 0.875em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-custom {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            padding: .5rem 1rem;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        let isAdminMode = false;\r\n");
      out.write("\r\n");
      out.write("        function toggleLoginMode() {\r\n");
      out.write("            isAdminMode = !isAdminMode;\r\n");
      out.write("\r\n");
      out.write("            if (isAdminMode) {\r\n");
      out.write("                document.getElementById(\"loginTitle\").innerText = \"Admin Login\";\r\n");
      out.write("                document.getElementById(\"formLogin\").action = \"admin/login\";\r\n");
      out.write("                document.getElementById(\"social-login\").style.display = \"none\";\r\n");
      out.write("                document.getElementById(\"captcha-box\").style.display = \"none\";\r\n");
      out.write("                document.getElementById(\"forgotPassword\").style.display = \"none\"; // Ẩn Forgot Password\r\n");
      out.write("                document.getElementById(\"switchButton\").innerText = \"Switch to Customer Login\";\r\n");
      out.write("            } else {\r\n");
      out.write("                document.getElementById(\"loginTitle\").innerText = \"Customer Login\";\r\n");
      out.write("                document.getElementById(\"formLogin\").action = \"login\";\r\n");
      out.write("                document.getElementById(\"social-login\").style.display = \"block\";\r\n");
      out.write("                document.getElementById(\"captcha-box\").style.display = \"block\";\r\n");
      out.write("                document.getElementById(\"forgotPassword\").style.display = \"inline-block\"; // Hiện lại Forgot Password\r\n");
      out.write("                document.getElementById(\"switchButton\").innerText = \"Switch to Admin Login\";\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/search_button_template.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/custom_background_template.css\"/>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    .dropdown-submenu {\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .submenu {\r\n");
      out.write("        display: none;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        left: 100%;\r\n");
      out.write("        z-index: 9999;\r\n");
      out.write("        min-width: 200px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dropdown-submenu:hover > .submenu {\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"background-div-header\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row align-items-center justify-content-between\" style=\"font-family: 'Roboto', sans-serif\">\r\n");
      out.write("            <div class=\"col-md-5 d-flex align-items-center\">\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"text-decoration: none; color: #0c0c0c\">\r\n");
      out.write("                    <h1 class=\"display-5\">\r\n");
      out.write("                        <img src=\"images/shirt-logo-black.png\" style=\"max-height: 100px\" class=\"img-fluid\">\r\n");
      out.write("                        The Store\r\n");
      out.write("                    </h1>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-6 d-flex align-items-center justify-content-end\">\r\n");
      out.write("                <!-- Categories Dropdown -->\r\n");
      out.write("                <div class=\"dropdown custom-dropdown me-2\">\r\n");
      out.write("                    <button class=\"btn btn-outline-primary dropdown-toggle\" type=\"button\" id=\"categoryMenu\"\r\n");
      out.write("                            data-bs-toggle=\"dropdown\" aria-expanded=\"false\" style=\"font-size: large\">\r\n");
      out.write("                        Categories\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <ul class=\"dropdown-menu\" id=\"category-menu\" aria-labelledby=\"categoryMenu\">\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Login / Logout -->\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <a href=\"view_cart\" class=\"btn custom-btn-cart ms-2\" style=\"font-size: large\">\r\n");
      out.write("                    <img src=\"images/online-shopping.png\" style=\"max-height: 20px;\">&nbsp;&nbsp;Cart\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Search -->\r\n");
      out.write("        <br>\r\n");
      out.write("        <div class=\"row justify-content-end mb-4\">\r\n");
      out.write("            <div class=\"col-md-5\" style=\"font-family: 'Roboto', sans-serif\">\r\n");
      out.write("                <form action=\"search\" method=\"get\" class=\"d-flex\">\r\n");
      out.write("                    <div class=\"input-group input-group-sm\">\r\n");
      out.write("                        <input type=\"text\" name=\"keyword\" class=\"cta_input\" placeholder=\"Search here\"/>\r\n");
      out.write("                        <button type=\"submit\" class=\"cta\">\r\n");
      out.write("                            <span class=\"span\">FIND</span>\r\n");
      out.write("                            <span class=\"second\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- JS xá»­ lÃ½ danh má»¥c nhiá»u cáº¥p -->\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function () {\r\n");
      out.write("        // Hiá»n thá» submenu khi hover\r\n");
      out.write("        $(document).on('mouseenter', '.category-item', function () {\r\n");
      out.write("            const $this = $(this);\r\n");
      out.write("            const catId = $this.data(\"id\");\r\n");
      out.write("            const $parentLi = $this.closest('li');\r\n");
      out.write("\r\n");
      out.write("            if ($parentLi.children('.submenu').length > 0) return;\r\n");
      out.write("\r\n");
      out.write("            $.get(\"/StoreWebsite/api/get_subcategories\", { parentId: catId }, function (subs) {\r\n");
      out.write("                if (subs && subs.length > 0) {\r\n");
      out.write("                    const submenu = $('<ul>', {\r\n");
      out.write("                        class: 'dropdown-menu submenu'\r\n");
      out.write("                    });\r\n");
      out.write("\r\n");
      out.write("                    subs.forEach(sub => {\r\n");
      out.write("                        const li = $('<li>', { class: 'dropdown-submenu' });\r\n");
      out.write("                        const a = $('<a>', {\r\n");
      out.write("                            class: 'dropdown-item category-item',\r\n");
      out.write("                            href: \"#\",\r\n");
      out.write("                            'data-id': sub.id,\r\n");
      out.write("                            text: sub.name\r\n");
      out.write("                        });\r\n");
      out.write("                        li.append(a);\r\n");
      out.write("                        submenu.append(li);\r\n");
      out.write("                    });\r\n");
      out.write("\r\n");
      out.write("                    $parentLi.append(submenu);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $(document).on('click', '.category-item', function (e) {\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            const id = $(this).data('id');\r\n");
      out.write("            if (id) {\r\n");
      out.write("                window.location.href = \"view_category?id=\" + id;\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"background-div-content\">\r\n");
      out.write("    <div class=\"container mb-5\">\r\n");
      out.write("        <div class=\"row justify-content-center\">\r\n");
      out.write("            <div class=\"row custom-row-1 mt-5 text-center\" style=\"width: fit-content\">\r\n");
      out.write("                <h2 id=\"loginTitle\">Customer Login</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"text-center mb-3\">\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-warning\" onclick=\"toggleLoginMode()\" id=\"switchButton\">\r\n");
      out.write("                Switch to Admin Login\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <br>\r\n");
      out.write("\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row justify-content-center text-center\">\r\n");
      out.write("            <div class=\"col-md-6 border custom-border\" style=\"border-radius: 20px; padding: 25px\">\r\n");
      out.write("                <form id=\"formLogin\" action=\"login\" method=\"post\">\r\n");
      out.write("                    <div class=\"mb-3 text-start\">\r\n");
      out.write("                        <label for=\"email\" class=\"form-label\">Email:</label>\r\n");
      out.write("                        <input type=\"email\" name=\"email\" id=\"email\" class=\"form-control\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"mb-3 text-start\">\r\n");
      out.write("                        <label for=\"password\" class=\"form-label\">Password:</label>\r\n");
      out.write("                        <input type=\"password\" name=\"password\" id=\"password\" class=\"form-control\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"mb-5 text-start\">\r\n");
      out.write("                        <a id=\"forgotPassword\" href=\"reset_password\" class=\"custom-btn-delete\" style=\"text-decoration: none; border-radius: 10px\">Forgot Password</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"mb-3\" id=\"captcha-box\">\r\n");
      out.write("                        <div class=\"h-captcha\" data-sitekey=\"ca61f481-d935-460c-aa2f-61f113c2fa54\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"row mt-3\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn custom-btn-login\" style=\"font-size: large\">Login</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div id=\"social-login\">\r\n");
      out.write("                        <div class=\"row mt-3\">\r\n");
      out.write("                            <a href=\"https://accounts.google.com/o/oauth2/auth?scope=email profile openid&redirect_uri=http://localhost:9999/StoreWebsite/login&response_type=code&client_id=633529606659-e1v70t8etd167p3n6b79emu5r9t5tu22.apps.googleusercontent.com&approval_prompt=force&state=provider=google\"\r\n");
      out.write("                               class=\"btn btn-lg btn-danger btn-custom\">\r\n");
      out.write("                                <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\"\r\n");
      out.write("                                     class=\"bi bi-google\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                    <path d=\"M15.545 6.558a9.42 9.42 0 0 1 .139 1.626c0 2.434-.87 4.492-2.384 5.885h.002C11.978 15.292 10.158 16 8 16A8 8 0 1 1 8 0a7.689 7.689 0 0 1 5.352 2.082l-2.284 2.284A4.347 4.347 0 0 0 8 3.166c-2.087 0-3.86 1.408-4.492 3.304a4.792 4.792 0 0 0 0 3.063h.003c.635 1.893 2.405 3.301 4.492 3.301 1.078 0 2.004-.276 2.722-.764h-.003a3.702 3.702 0 0 0 1.599-2.431H8v-3.08h7.545z\"/>\r\n");
      out.write("                                </svg>\r\n");
      out.write("                                <span class=\"ms-2 fs-6\">Sign in with Google</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"row mt-3\">\r\n");
      out.write("                            <a href=\"https://www.facebook.com/v21.0/dialog/oauth?client_id=8898839156821098&redirect_uri=http://localhost:9999/StoreWebsite/login&state=provider=facebook&scope=email\"\r\n");
      out.write("                               class=\"btn btn-lg btn-primary btn-custom\">\r\n");
      out.write("                                <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\"\r\n");
      out.write("                                     class=\"bi bi-facebook\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                    <path d=\"M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z\"/>\r\n");
      out.write("                                </svg>\r\n");
      out.write("                                <span class=\"ms-2 fs-6\">Sign in with Facebook</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/custom_row_template.css\"/>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row custom-row-footer fs-5\">\r\n");
      out.write("	<div class=\"col-2 mb-3 mt-3\">\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"col-4 mb-3 mt-3\">\r\n");
      out.write("		<p><strong>Contact us</strong></p>\r\n");
      out.write("		<p><b>Email:</b> support@theshirtstore.com</p>\r\n");
      out.write("		<p><b>Hotline:</b> 0123 465 789</p>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"col-3 mb-3 mt-3\">\r\n");
      out.write("		<p><a href=\"frontend/about.jsp\" style=\"text-decoration: none; color: #FFFFFF\">About us</a></p>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"col-3 mb-3 mt-3\">\r\n");
      out.write("		<p><b>Policies</b></p>\r\n");
      out.write("		<p><a href=\"frontend/privacy_policy.jsp\" style=\"text-decoration: none; color: #FFFFFF\">Privacy Policy</a></p>\r\n");
      out.write("		<p><a href=\"frontend/terms.jsp\" style=\"text-decoration: none; color: #FFFFFF\">Terms and Conditions agreement</a></p>\r\n");
      out.write("		<p><a href=\"frontend/return_policy.jsp\" style=\"text-decoration: none; color: #FFFFFF\">Return and Refund Policy</a></p>\r\n");
      out.write("		<p><a href=\"frontend/disclaimer.jsp\" style=\"text-decoration: none; color: #FFFFFF\">Disclaimer</a></p>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row custom-row text-center\">\r\n");
      out.write("	<div class=\"col mb-1 mt-1\">\r\n");
      out.write("		<p><b>Copyright &copy; 2024 by The Shirt Store. All rights reserved.</b></p>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(function () {\r\n");
      out.write("        window.addEventListener(\"load\", () => {\r\n");
      out.write("            const loader = document.querySelector(\".loader_wrapper\");\r\n");
      out.write("            setTimeout(() => {\r\n");
      out.write("                loader?.classList.add(\"loader-hidden\");\r\n");
      out.write("                loader?.addEventListener(\"transitionend\", () => {\r\n");
      out.write("                    document.body.removeChild(loader);\r\n");
      out.write("                });\r\n");
      out.write("            }, 500);\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        function getMessageContent(messageId, event) {\r\n");
      out.write("            fetch('csvdata?id=' + messageId)\r\n");
      out.write("                .then(response => response.json())\r\n");
      out.write("                .then(data => {\r\n");
      out.write("                    if (data.message) {\r\n");
      out.write("                        Swal.fire(data.message);\r\n");
      out.write("                        event.preventDefault();\r\n");
      out.write("                    } else {\r\n");
      out.write("                        Swal.fire(\"Message not found\");\r\n");
      out.write("                        event.preventDefault();\r\n");
      out.write("                    }\r\n");
      out.write("                })\r\n");
      out.write("                .catch(error => console.error(\"Error: \", error));\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $(\"#formLogin\").submit(function (event) {\r\n");
      out.write("            const email = $(\"#email\").val();\r\n");
      out.write("            const password = $(\"#password\").val();\r\n");
      out.write("            const emailRegex = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$/;\r\n");
      out.write("\r\n");
      out.write("            if (email.trim() === \"\") {\r\n");
      out.write("                getMessageContent(\"NOT_NULL_EMAIL\", event);\r\n");
      out.write("            } else if (!emailRegex.test(email)) {\r\n");
      out.write("                getMessageContent(\"INVALID_EMAIL_ADDRESS\", event);\r\n");
      out.write("            } else if (password.trim() === \"\") {\r\n");
      out.write("                getMessageContent(\"NOT_NULL_PASSWORD\", event);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $(\"#formLogin\").validate({\r\n");
      out.write("            rules: {\r\n");
      out.write("                email: \"required\",\r\n");
      out.write("                password: \"required\"\r\n");
      out.write("            },\r\n");
      out.write("            messages: {\r\n");
      out.write("                email: \"\",\r\n");
      out.write("                password: \"\",\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /frontend/header.jsp(45,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("category");
      // /frontend/header.jsp(45,24) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/frontend/header.jsp(45,24) '${parentList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${parentList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                            <li class=\"dropdown-submenu\">\r\n");
            out.write("                                <a class=\"dropdown-item category-item\" href=\"#\" data-id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                                    ");
            if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("                                </a>\r\n");
            out.write("                            </li>\r\n");
            out.write("                        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /frontend/header.jsp(48,36) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.name}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /frontend/header.jsp(56,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loggedCustomer != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    <div class=\"dropdown custom-dropdown\">\r\n");
          out.write("                        <button class=\"btn btn-dark dropdown-toggle\" type=\"button\" id=\"userMenu\"\r\n");
          out.write("                                data-bs-toggle=\"dropdown\" aria-expanded=\"false\" style=\"font-size: large\">\r\n");
          out.write("                            Hi there, ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loggedCustomer.firstname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(' ');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loggedCustomer.lastname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("                        </button>\r\n");
          out.write("                        <ul class=\"dropdown-menu dropdown-menu-end\" aria-labelledby=\"userMenu\">\r\n");
          out.write("                            <li><a class=\"dropdown-item\" href=\"view_profile\">Profile</a></li>\r\n");
          out.write("                            <li><a class=\"dropdown-item\" href=\"view_orders\">My Orders</a></li>\r\n");
          out.write("                            <li><a class=\"dropdown-item\" href=\"logout\">Logout</a></li>\r\n");
          out.write("                        </ul>\r\n");
          out.write("                    </div>\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /frontend/header.jsp(70,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loggedCustomer == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    <a href=\"login\" class=\"btn custom-btn-login\" style=\"font-size: large\">Login</a>\r\n");
          out.write("                    <a href=\"register\" class=\"btn custom-btn-signup ms-2\" style=\"font-size: large\">Sign up</a>\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /frontend/login.jsp(78,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            <div class=\"row justify-content-center\">\r\n");
          out.write("                <div class=\"col-md-6\">\r\n");
          out.write("                    <div class=\"alert alert-danger\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("                </div>\r\n");
          out.write("            </div>\r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
